```python
# Generated by Django 5.2.10 on 2026-01-17 21:15

# Phase 6: Deploy para Produção (GitHub/Render)
# - [x] Hardening: Configurar ALLOWED_HOSTS e WhiteNoise
# - [x] Hardening: Configurar dj-database-url
# - [x] Criar Procfile e requirements.txt
# - [x] Inicializar Git e Push para GitHub
# - [x] Configurar Render (Instruções finais enviadas)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nome do Lead"),
                ),
                (
                    "contact_info",
                    models.CharField(max_length=255, verbose_name="WhatsApp/Email"),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[
                            ("LIPEDEMA", "Lipedema/Saúde"),
                            ("SUPER", "Superendividamento"),
                            ("CULTURAL", "Lei Rouanet/Cultural"),
                            ("OTHER", "Outros Assuntos"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Caso",
                    ),
                ),
                ("triage_data", models.JSONField(blank=True, default=dict)),
                ("score", models.IntegerField(default=0)),
                ("is_qualified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
            },
        ),
        migrations.CreateModel(
            name="TriageSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100, unique=True)),
                ("current_step", models.IntegerField(default=1)),
                ("temp_data", models.JSONField(default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
