# Generated by Django 5.2.10 on 2026-01-18 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="ID do caso no sistema Legal Ops",
                max_length=255,
                null=True,
                verbose_name="ID Externo (Clio/Jestor)",
            ),
        ),
    ]
