# Generated by Django 4.2.9 on 2026-01-20 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0002_add_external_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="location",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Localização (Cidade/Estado)"
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(
                blank=True,
                default="Orgânico",
                max_length=100,
                verbose_name="Fonte do Lead",
            ),
        ),
    ]
