# Generated by Django 5.2.10 on 2026-01-20 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0003_lead_location_lead_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="viability_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Em Análise"),
                    ("HIGH", "Alta Probabilidade"),
                    ("MEDIUM", "Média Probabilidade"),
                    ("LOW", "Baixa Probabilidade"),
                    ("REJECTED", "Inviável"),
                ],
                default="PENDING",
                max_length=20,
                verbose_name="Viabilidade",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="is_qualified",
            field=models.BooleanField(default=False, verbose_name="Qualificado?"),
        ),
        migrations.AlterField(
            model_name="lead",
            name="score",
            field=models.IntegerField(
                default=0,
                help_text="Pontuação de viabilidade (0-100)",
                verbose_name="ClaimScore",
            ),
        ),
        migrations.CreateModel(
            name="LeadAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField(verbose_name="Resumo Executivo")),
                (
                    "positive_points",
                    models.JSONField(default=list, verbose_name="Pontos Fortes"),
                ),
                (
                    "negative_points",
                    models.JSONField(default=list, verbose_name="Pontos de Atenção"),
                ),
                (
                    "recommended_action",
                    models.CharField(max_length=255, verbose_name="Ação Recomendada"),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis",
                        to="intake.lead",
                    ),
                ),
            ],
        ),
    ]
