# Generated by Django 5.2.10 on 2026-01-20 04:51

import core.security.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0004_lead_viability_status_alter_lead_is_qualified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="contact_info",
            field=core.security.fields.EncryptedField(
                help_text="Dados sensíveis criptografados",
                max_length=255,
                verbose_name="WhatsApp/Email",
            ),
        ),
    ]
