# Generated by Django 5.2.10 on 2026-01-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("intake", "0005_alter_lead_contact_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="case_type",
            field=models.CharField(
                choices=[
                    ("LIPEDEMA", "Lipedema/Saúde"),
                    ("SUPER", "Superendividamento"),
                    ("CULTURAL", "Lei Rouanet/Cultural"),
                    ("CIVIL", "Cível/Contratos"),
                    ("INTERNSHIP", "Candidatura a Estágio"),
                    ("OTHER", "Outros Assuntos"),
                ],
                max_length=20,
                verbose_name="Tipo de Caso",
            ),
        ),
    ]
