# Generated by Django 5.2.10 on 2026-01-18 01:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        ("legal_cases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("PETITION", "Petição Inicial"),
                            ("EVIDENCE", "Documento Probatório"),
                            ("COURT_ORDER", "Decisão Judicial"),
                            ("CORRESPONDENCE", "Correspondência"),
                            ("CONTRACT", "Contrato/Acordo"),
                            ("OTHER", "Outro"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Título")),
                ("description", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "file",
                    models.FileField(
                        upload_to="case_documents/%Y/%m/", verbose_name="Arquivo"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Upload"
                    ),
                ),
                (
                    "is_visible_to_client",
                    models.BooleanField(
                        default=True,
                        help_text="Se desmarcado, apenas advogados podem ver",
                        verbose_name="Visível para Cliente",
                    ),
                ),
                (
                    "legal_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="legal_cases.legalcase",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enviado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento do Caso",
                "verbose_name_plural": "Documentos dos Casos",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="CaseTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_stage",
                    models.CharField(
                        choices=[
                            ("INTAKE", "Triagem Inicial"),
                            ("ANALYSIS", "Análise Jurídica"),
                            ("PETITION", "Petição Elaborada"),
                            ("FILED", "Protocolo Realizado"),
                            ("DISCOVERY", "Fase Instrutória"),
                            ("HEARING", "Audiência Agendada"),
                            ("DECISION", "Sentença Proferida"),
                            ("APPEAL", "Recurso Interposto"),
                            ("CLOSED", "Caso Encerrado"),
                        ],
                        default="INTAKE",
                        max_length=20,
                        verbose_name="Etapa Atual",
                    ),
                ),
                (
                    "milestones",
                    models.JSONField(
                        default=list,
                        help_text="Lista de {stage, date, notes, updated_by}",
                        verbose_name="Marcos do Processo",
                    ),
                ),
                (
                    "last_update",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Atualização"
                    ),
                ),
                (
                    "legal_case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeline",
                        to="legal_cases.legalcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Linha do Tempo",
                "verbose_name_plural": "Linhas do Tempo",
            },
        ),
        migrations.CreateModel(
            name="ClientPortalAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(
                        help_text="Token único para acesso ao portal",
                        max_length=64,
                        unique=True,
                        verbose_name="Token de Acesso",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "last_accessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Último Acesso"
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="portal_access",
                        to="clients.client",
                    ),
                ),
                (
                    "legal_case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="legal_cases.legalcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acesso ao Portal",
                "verbose_name_plural": "Acessos ao Portal",
                "unique_together": {("client", "legal_case")},
            },
        ),
    ]
