# Generated by Django 5.2.10 on 2026-01-20 01:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HumanRightsCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=255, verbose_name="Nome da Vítima/Caso"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("SEC_20", "Século XX (1901-2000)"),
                            ("SEC_21", "Século XXI (2001-Presente)"),
                        ],
                        max_length=20,
                        verbose_name="Período Histórico",
                    ),
                ),
                (
                    "violation_type",
                    models.CharField(
                        choices=[
                            ("CENSURA", "Censura e Liberdade de Expressão"),
                            ("TORTURA", "Tortura e Tratamento Desumano"),
                            ("TRABALHO_ESCRAVO", "Trabalho Análogo à Escravidão"),
                            ("VIOLENCIA_POLICIAL", "Violência Policial / Letalidade"),
                            ("PERSEGUICAO_POLITICA", "Perseguição Política"),
                            (
                                "NEGLIGENCIA_ESTATAL",
                                "Negligência Estatal / Saúde / Educação",
                            ),
                            (
                                "DIREITOS_INDIGENAS",
                                "Violação de Direitos Indígenas/Ambientais",
                            ),
                            (
                                "DISCRIMINACAO",
                                "Discriminação (Raca, Gênero, Orientação)",
                            ),
                            ("MASSACRE", "Massacres e Chacinas"),
                        ],
                        max_length=50,
                        verbose_name="Tipo de Violação",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descrição do Caso")),
                (
                    "date_event",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Data do Evento (Aprox)",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=100, verbose_name="Localização (Estado/Cidade)"
                    ),
                ),
                (
                    "impact_level",
                    models.IntegerField(
                        default=5, verbose_name="Nível de Impacto Histórico (1-10)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            (
                                "RECONHECIDO",
                                "Reconhecido pelo Estado (Anistia/Indenização)",
                            ),
                            ("EM_ANALISE", "Em Análise / Judicializado"),
                            ("IMPUNE", "Impune / Arquivado"),
                            ("MEMORIA", "Memória/Legado (Sem resolução judicial)"),
                        ],
                        default="MEMORIA",
                        max_length=50,
                        verbose_name="Status Jurídico/Histórico",
                    ),
                ),
                (
                    "source_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Fonte/Referência"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="Imagem (URL)"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Caso de Direitos Humanos",
                "verbose_name_plural": "Observatório - Casos",
                "ordering": ["-date_event"],
            },
        ),
    ]
