# Generated by Django 4.2.9 on 2026-01-19 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("whatsapp_enabled", models.BooleanField(default=True)),
                ("clio_integration_active", models.BooleanField(default=False)),
                ("jestor_integration_active", models.BooleanField(default=False)),
                ("client_notification_auto", models.BooleanField(default=True)),
                ("token_validity_days", models.IntegerField(default=30)),
                (
                    "office_name",
                    models.CharField(default="Alessandra M. Donadon", max_length=200),
                ),
            ],
            options={
                "verbose_name": "Configurações do Sistema",
                "verbose_name_plural": "Configurações do Sistema",
            },
        ),
    ]
