# Generated by Django 5.2.10 on 2026-01-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountPayable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "supplier",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Fornecedor"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Valor (R$)"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("PAID", "Pago"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("OFFICE", "Escritório"),
                            ("SOFTWARE", "Software/Sistemas"),
                            ("MARKETING", "Marketing"),
                            ("LEGAL_FEES", "Custas Processuais"),
                            ("TAXES", "Impostos"),
                            ("OTHER", "Outros"),
                        ],
                        default="OTHER",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Conta a Pagar",
                "verbose_name_plural": "Contas a Pagar",
                "ordering": ["due_date"],
            },
        ),
    ]
