# Generated by Django 4.2.9 on 2026-01-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "legal_cases",
            "0002_legalcase_contingency_value_legalcase_risk_level_and_more",
        ),
        ("finance", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountReceivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nome do Cliente"
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Valor (R$)"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Data de Vencimento")),
                (
                    "received_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Recebimento"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("RECEIVED", "Recebido"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FEES", "Honorários"),
                            ("REIMBURSEMENT", "Reembolso de Custas"),
                            ("SUCCESS_FEE", "Honorários de Êxito"),
                            ("OTHER", "Outros"),
                        ],
                        default="FEES",
                        max_length=20,
                        verbose_name="Categoria",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Observações")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "legal_case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivables",
                        to="legal_cases.legalcase",
                    ),
                ),
            ],
            options={
                "verbose_name": "Conta a Receber",
                "verbose_name_plural": "Contas a Receber",
                "ordering": ["due_date"],
            },
        ),
    ]
