# Generated by Django 5.2.10 on 2026-01-21 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("in_brief", "0002_alter_article_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="articles/"),
        ),
    ]
