# Generated by Django 5.2.10 on 2026-01-17 19:35

import core.security.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Título da Causa"),
                ),
                (
                    "process_number",
                    core.security.fields.EncryptedField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Número do Processo",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("CIVIL", "Cível"),
                            ("BUSINESS", "Empresarial"),
                            ("HEALTH", "Saúde (Lipedema)"),
                            ("THIRD_SECTOR", "Terceiro Setor (Lei Rouanet)"),
                            ("OTHER", "Outros"),
                        ],
                        default="CIVIL",
                        max_length=20,
                        verbose_name="Área de Atuação",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ANALYSIS", "Em Análise"),
                            ("ACTIVE", "Ativo"),
                            ("SUSPENDED", "Suspenso"),
                            ("ARCHIVED", "Arquivado"),
                        ],
                        default="ANALYSIS",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Descrição/Anotações"),
                ),
                (
                    "entry_date",
                    models.DateField(auto_now_add=True, verbose_name="Data de Entrada"),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="clients.client",
                    ),
                ),
            ],
            options={
                "verbose_name": "Caso Jurídico",
                "verbose_name_plural": "Casos Jurídicos",
            },
        ),
    ]
