# Generated by Django 4.2.9 on 2026-01-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("legal_cases", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="legalcase",
            name="contingency_value",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=12,
                verbose_name="Valor da Causa/Contingência",
            ),
        ),
        migrations.AddField(
            model_name="legalcase",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("LOW", "Baixo - Provável Êxito"),
                    ("MEDIUM", "Médio - Possível Êxito"),
                    ("HIGH", "Alto - Remoto Êxito"),
                ],
                default="LOW",
                max_length=10,
                verbose_name="Nível de Risco (Contingência)",
            ),
        ),
        migrations.AlterField(
            model_name="legalcase",
            name="area",
            field=models.CharField(
                choices=[
                    ("CIVIL", "Direito Cível"),
                    ("BUSINESS", "Direito Empresarial"),
                    ("HEALTH", "Saúde (Lipedema)"),
                    ("THIRD_SECTOR", "Terceiro Setor (Lei Rouanet)"),
                    ("OTHER", "Outros"),
                ],
                max_length=20,
                verbose_name="Área de Atuação",
            ),
        ),
        migrations.AlterField(
            model_name="legalcase",
            name="description",
            field=models.TextField(blank=True, verbose_name="Descrição/Observações"),
        ),
        migrations.AlterField(
            model_name="legalcase",
            name="last_update",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Atualização"
            ),
        ),
        migrations.AlterField(
            model_name="legalcase",
            name="process_number",
            field=models.CharField(
                blank=True,
                default="",
                max_length=100,
                verbose_name="Número do Processo",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="legalcase",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Título do Caso"),
        ),
    ]
