# Generated by Django 5.2.10 on 2026-01-17 19:35

import core.security.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Nome Completo"),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[("PF", "Pessoa Física"), ("PJ", "Pessoa Jurídica")],
                        default="PF",
                        max_length=2,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "cpf_cnpj",
                    core.security.fields.EncryptedField(
                        help_text="Stored encrypted",
                        max_length=255,
                        unique=True,
                        verbose_name="CPF/CNPJ",
                    ),
                ),
                (
                    "phone",
                    core.security.fields.EncryptedField(
                        help_text="Stored encrypted",
                        max_length=255,
                        verbose_name="Telefone/WhatsApp",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-mail"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-created_at"],
            },
        ),
    ]
