# Generated by Django 5.2.10 on 2026-01-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROSPECT", "Potencial / Em Negociação"),
                    ("ONBOARDING", "Onboarding / Entrada"),
                    ("ACTIVE", "Ativo / Recorrente"),
                    ("ARCHIVED", "Inativo / Arquivado"),
                ],
                default="ACTIVE",
                max_length=20,
                verbose_name="Status",
            ),
        ),
    ]
